Ayush
OpencodeNIT-R/project-athena pull request #1
Opened 2023-12-10 09:04 UTC by SingAyush

2023-12-10 11:16 UTC, Shurtu-gal requested changes
Are the css.jsx files needed?

2023-12-10 11:16 UTC, Shurtu-gal commented on src/app/page.js
Contents can be removed

2023-12-12 07:25 UTC, SingAyush commented on src/app/page.js
done

2023-12-14 05:24 UTC, SingAyush reviewed
done

2023-12-14 05:36 UTC, merged